### ISSUE TITLE
Anvil F8C Lightning missing

### ISSUE THREAD

**Issue by Stuntedgrowth** [Raylehnhoff/SCFSD#100]
Pretty minor as only backers wing commander+ get access to it afaik, but it's not in the ship list that I can see

**Comment by ElArGee** [comment]
Currently there isn't much reference for the Lightning, so I haven't included it. I'm curious as to whether there is a holoviewer model for it though? If there is I can pretty easily add it in. Either that or a clear profile shot of the ship would probably be ok for making a silhouette.

**Comment by Stuntedgrowth** [comment]
Yeah I searched around, it's got no listing in the ship matrix, so no
holoviewer. There was the old 2013 leak greybox renders, but aside from
being old, they're all angled/top down views, so no luck there. Ah well, no
big deal, it's only e-peen! hah.

Ty for the response though

**Comment by Raylehnhoff** [comment]
Closing -- if you can find a viable silhouette we can use, let us know.
