### ISSUE TITLE
Download as image bug

### ISSUE THREAD

**Issue by senNish** [Raylehnhoff/SCFSD#12]
Clicking download as image saves an image with only the background showing.

**Comment by Raylehnhoff** [comment]
Please add additional information, such as browser and inputs used.

**Comment by Mccluvinn** [comment]
i'm having the same issue, it happens on all browsers i tried (Firefox, Chrome, and Edge) i ended up just doing from my phone and transferring it to my computer. Not sure what it could be.....

**Comment by Raylehnhoff** [comment]
This bug seems to be caused by HTTPs anywhere. I committed some code today that - I think - should resolve it. If you find that this is still an issue, please let me know.

**Comment by Raylehnhoff** [comment]
Seeing no further activity on this issue, I'm going to close it.
