### ISSUE TITLE
Page freeze after adding ships

### ISSUE THREAD

**Issue by ElArGee** [Raylehnhoff/SCFSD#15]
As you add more ships to the chart, the freeze gets longer.

Profiling the scripts that run after adding ships suggests the freeze could be originating here: [html2canvas.js:742](https://github.com/Raylehnhoff/SCFSD/blob/V2/content/ThirdParty/html2canvas.js#L742)

I found the freeze only became noticeable after about 500 ships with roughly a 2 second freeze. 1000 ships = 4 seconds. 2000 ships = 8 seconds. 4000 ships = 16 seconds. etc.

After the freeze there are a ton of function calls to [html2canvas.js:2696](https://github.com/Raylehnhoff/SCFSD/blob/V2/content/ThirdParty/html2canvas.js#L2696) after which the download link becomes available. 

Tested on Chrome, Firefox, and Edge

**Comment by Raylehnhoff** [comment]
Yeah, I need to re think the redraw pipeline to prevent this behavior.
Thanks for profiling it, I just haven't gotten there yet

**Comment by ElArGee** [comment]
Is it possible to only redraw the downloaded image after pressing the download button? Currently it seems to be redrawing the png after every change.

**Comment by Raylehnhoff** [comment]
I overhauled the save pipeline, initial testing shows that it's behaving within acceptable means for larger image sets. Give it a whirl. If you're unconvinced then re-open.

**Comment by ElArGee** [comment]
Seems to be working well :+1: 

No latency when adding ships from what I can tell.
