### ISSUE TITLE
Order ships alphabetically and/or categorise by maker (eg. Misc)?

### ISSUE THREAD

**Issue by moozaad** [Raylehnhoff/SCFSD#16]
It's getting a bit much to find them. Ordering by size is fine in the image.

**Comment by Raylehnhoff** [comment]
The ships are ordered according to size, since currently the order they appear in in the list is also the order they're output in. @Loganbacca can comment on this issue to see if he thinks there's a better way.

**Comment by ElArGee** [comment]
Currently the ships are sorted loosely by role and size so the final chart looks ordered. I have been considering sorting by manufacturer then alphabetically. I'll try a few things out and see how it looks.

**Comment by moozaad** [comment]
I just had a look at the V2 and the constant scrolling to find the ships is not a great UX. The massive input box for a small number seems excessive and could easily be reduced.

I have the following suggestions:

Place the input to the left and wide enough for 4 digits, followed by a + then - button separate to the input. Followed by the ship name.

eg.
`[ #### ] [+] [-] Ship name`

At the very top have a dropdown to easily order the ship by name or size.

Or even better, use something like jquery datatables and have the image on a separate tab.
https://www.datatables.net/examples/basic_init/zero_configuration.html
If you were doing something like that thought, you'd probably want to also do json to handle ship data to populate model, make, size, role, icon etc. /feature creep

**Comment by Raylehnhoff** [comment]
I'm not currently seeking feedback on v2. I'll take it under consideration
but that's not a concern at this time.

**Comment by Raylehnhoff** [comment]
Also @moozaad, all of the data internally is JSON which was a major overhaul in V2.

In V2, adding a new ship is a matter of adding it to the [Static](https://github.com/Raylehnhoff/SCFSD/blob/V2/content/scripts/Static.js) file. If @Loganbacca wanted to pursue adding meta data about the ships, it'd be a matter of adding it there. I don't necessarily agree that having that kind of data is in keeping with the spirit of this application though. 

This tool was built (and maintained) with the singular purpose of letting organizations display their fleets. I think we're getting lost in the wood if we also become an information trove of ship dimensions. It'd even reduce functionality in cases when we know what a ship looks like, but not its dimensions. In such a case, where would we file it? It's a contrived example, but it's not terribly rare.

I thought about having the rendered image on a separate tab, but after trying it, I felt like that UX was inferior to V1 (which is pretty bad itself). People **want** to see immediate changes on an app like this. Tucking the graphic on another tab removes that.

I think that I can solve the constant scrolling issue in two ways, neither of them adding significant work: 
1. Reduce input sizes to input-sm (basically what you suggested)
2. Add a search box, which would filter the result set down to whatever ship name matches the input. I built a very similar tool [here](http://raylehnhoff.github.io/Have-I-Cubed-This-Yet/) that has this behavior.

I'm confused as to what the [+] and [-] would do exactly? If they're just there to give space between the inputs, why wouldn't this be solved using margin? 

I apologize for being dismissive initially. UX should be a top priority, but not at the expense of fixing major issues or getting the new feature set to a good place. This is particularly true when there's only one time-constrained developer doing the work :)

**Comment by ElArGee** [comment]
Here's a couple of examples for consideration:

Current: http://i.imgur.com/Du1Rbu9.png

Grouped by manufacturer: http://i.imgur.com/65LUi7R.png

Any thoughts on the two @moozaad and @Raylehnhoff? I personally wasn't fond of the manufacturer grouping while reordering it, but now looking at the image as a whole I like the fact it isn't so top heavy.

This is basically a holdover solution for this issue; i.e. reordering the current chart until an actual sorting mechanism is added.

**Comment by Raylehnhoff** [comment]
@Loganbacca, I've pushed Milestone V2 to github-pages, rebasing that repository. I'm not considering it "done", but it's good enough at this point.

I'd like to discuss this matter further if we want to look to different ordering preferences. I'm not against the idea, but we need to come up with something that works for everyone.

**Comment by ElArGee** [comment]
Is it possible to acquire the width of the ship's svg file? Seeing as they're xml, and have a "width"attribute, surely we can just pull the size for sorting from that? 

Manufacturer could just be added as another argument in the static file, and to me including manufacturer doesn't seem like it would be out of scope, or much effort. 

From there you've got 3 attributes to sort by: size, manufacturer, and name.

**Comment by Raylehnhoff** [comment]
@Loganbacca -- I think we could, yes. I'd need to play with how ordering it in different ways would impact the layouts. I assume if we grouped by Manufacturer, we'd want to output the Manufacturer name somewhere, but I'm not sure. I definitely haven't had a lot of time to really think about this.

**Comment by Raylehnhoff** [comment]
@Loganbacca -- Since I didn't want this issue to turn 2, I decided to tackle it today.

Ordering by width alone isn't a good measure, because some ships are tall but very skinny. I was thinking about ordering by the total area (width*height) -- this yields a decent ordering:

https://i.imgur.com/A2fn2OR.png

What are your thoughts on doing this? It would order them both in the name list AND in the output, so it would be very consistent and wouldn't require you to do anything special. It reads the width/height directly off of the svg.
