### ISSUE TITLE
RGB colour picker instead of fixed drop down

### ISSUE THREAD

**Issue by moozaad** [Raylehnhoff/SCFSD#17]
See LGPL  example http://jscolor.com/

**Comment by Raylehnhoff** [comment]
I've been working on v2 of this application which already includes this functionality.

**Comment by moozaad** [comment]
Sorry, I wasn't aware of v2. Is it up for testing anywhere and is there a list of features ?

**Comment by Raylehnhoff** [comment]
You can switch the branch to v2 and pull it. I haven't written up a feature
list but it's a significant update
