### ISSUE TITLE
v2, header URI should be explicit

### ISSUE THREAD

**Issue by moozaad** [Raylehnhoff/SCFSD#18]
```
<link href="//fonts.googleapis.com/css?family=Electrolize" media="all" rel="Stylesheet">
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js">/script>
```

Both missing "http:" so that it does work if you open it as a file://.

**Comment by Raylehnhoff** [comment]
Doing this breaks the addon https everywhere, and protocolless uris is
considered a best practice. This isn't meant to be ran from a local
directory, but from a proper local web server, which would give it a uri of
http://localhost/scfsd
