### ISSUE TITLE
Verify SCFSD has all current SC ships

### ISSUE THREAD

**Issue by Raylehnhoff** [Raylehnhoff/SCFSD#20]
This is an investigative issue -- I want to verify that we have all current ships in V2. I suspect the answer is "Yes". If we're good, feel free to tick the box correspond to this requirement on the V2 milestone.

**Comment by ElArGee** [comment]
The complete list:
- [x] Aurora
- [x] Constellation
- [x] Orion
- [x] 300
- [x] 890 Jump
- [x] 85X (unavailable for direct purchase)
- [x] M50
- [x] Avenger
- [x] Gladius
- [x] Idris
- [x] Javelin
- [x] Reclaimer
- [x] Redeemer
- [x] Retaliator
- [x] Vanguard
- [x] Cutlass
- [x] Caterpillar
- [x] Herald
- [x] Carrack
- [x] Gladiator
- [x] Hornet
- [x] Endeavor
- [x] Freelancer
- [x] Hull A
- [x] Hull B
- [x] Hull C
- [x] Hull D
- [x] Hull E
- [x] Reliant
- [x] Starfarer
- [x] P-52 Merlin
- [x] Mustang
- [x] Genesis
- [x] Scythe
- [x] Glaive
- [x] Khartu
- [x] Merchantman
