### ISSUE TITLE
Custom colours don't work

### ISSUE THREAD

**Issue by ElArGee** [Raylehnhoff/SCFSD#23]
Using the hex colour editor to change the ship, background, or font to a custom colour that isn't on the colour picker does not work.

**Comment by ElArGee** [comment]
A quick fix for this could be to remove the hex input box from the colour picker.

**Comment by Raylehnhoff** [comment]
That won't be necessary. I'll debug it later today and see what's going on.
Good catch.

**Comment by ElArGee** [comment]
Checked this out today and it's working really well :+1:
