### ISSUE TITLE
Archimedes/Crucible not present in the list

### ISSUE THREAD

**Issue by Dovakhan** [Raylehnhoff/SCFSD#24]
The new ships of this Anniversary sale are missing:
- Anvil Crucible.
- P-72 Archimedes.

**Comment by Raylehnhoff** [comment]
@Loganbacca, would you mind tackling this? I'm hoping to push V2 live this weekend, so you can just make the change there.

Thanks!

**Comment by ElArGee** [comment]
Yep, they're actually already in the V2 branch. 
On 27 Nov 2015 08:36, Ray notifications@github.com wrote:@Loganbacca, would you mind tackling this? I'm hoping to push V2 live this weekend, so you can just make the change there.

Thanks!
