### ISSUE TITLE
ships stay hex value #000000

### ISSUE THREAD

**Issue by Jarvvski** [Raylehnhoff/SCFSD#25]
even when modifying value for ship colour in options, colour remains #000000

**Comment by ElArGee** [comment]
Just tested this in Chrome and although at first the colour wouldn't change, after Ctrl+F5'ing the issue went away and the ship colours now change.
Note: I hadn't used the github.io site for V2 until now.

Can you confirm this works @Jarvvski ?

**Comment by Jarvvski** [comment]
@Loganbacca 
I got it to work via that method too, just took some messing around.

**Comment by Raylehnhoff** [comment]
I think this happened because the old file was cached. A CTRL+F5 causes a 'hard refresh', clearing out the cached files. Seeing as I haven't heard any other reports of this either here or on Reddit, I'm going to close this issue.
