### ISSUE TITLE
additional craft

### ISSUE THREAD

**Issue by ravon2109** [Raylehnhoff/SCFSD#40]
please include the terrapin thanks , also , grey cat , ursa rover etc.. as all vehicles would be good not just ships , when showing off your fleet

**Comment by Raylehnhoff** [comment]
@Loganbacca, thoughts on adding the rovers and smaller vehicles to this tool? I feel like it's a bit out-of-scope but I wanted to see if that's something you wanted to mess with or not.

**Comment by ElArGee** [comment]
It's not hard to add them, although the PTV will be tiny. The Ursa is also not available publicly yet, so that won't be in for a while.

We have the Dragonfly in already as well, which isn't technically a ship.

**Comment by ravon2109** [comment]
It was just the terrapin really you do what you think best, it's a wicked
little app thanks

**Comment by RommelTJ** [comment]
FWIW, I don't think you should add non-ships to a faction ship drawer. People can fork the project for their specific cases. Great app, btw.

**Comment by Raylehnhoff** [comment]
My biggest concern for adding non-ships is that it takes @Loganbacca's time, and that it would look awkward scale-wise. Since the tool rewrite several months ago, adding new items is pretty easy on the code side.

@RommelTJ -- thanks for the feedback. I'm inclined to agree, but at the same time the tool certainly has evolved a lot over what it was before.

**Comment by RommelTJ** [comment]
@Raylehnhoff So, if you're adding things like greycats, rovers, and Dragonflies, would you also add things like jetpacks? Soon, you will be implementing a full inventory system and it will become a maintenance nightmare. It's a better use of your time to focus on doing ships really well, like ability to customize the ship images, resize them, label them, colors, damage-states, etc. My 2-cents.

**Comment by Raylehnhoff** [comment]
Fair point. I'm inclined to agree with you that introducing smaller vehicles would become massive scope creep.

#41 added the terrapin, which was the core of this issue. Going to close it out since that branch was merged in.
