### ISSUE TITLE
Add Polaris

### ISSUE THREAD

**Issue by rlalley** [Raylehnhoff/SCFSD#44]
Polaris is not in the list.

**Comment by ElArGee** [comment]
On it. I'll get it added later today.

**Comment by rlalley** [comment]
It looks like an inaccurate size for the Polaris was used. It should be 155m, which makes it 3 meters short of the reclaimer of 158m. The image size doesn't appear to show a 3 meter difference.

**Comment by Raylehnhoff** [comment]
@rlalley see #48
