### ISSUE TITLE
Investigate grouping for non-space faring ships

### ISSUE THREAD

**Issue by Raylehnhoff** [Raylehnhoff/SCFSD#65]

**Comment by ElArGee** [comment]
Currently the order of ships is manually sorted in [Static.js](https://github.com/Raylehnhoff/SCFSD/blob/gh-pages/content/scripts/Static.js)

A few options I can think of:
- Manually group vehicles together
- Allow users to rearrange the order of ships to wherever they want
- Add metadata and a sorting filter (manufacturer, type, size, alphabetical, etc.)

**Comment by Raylehnhoff** [comment]
I think the easiest option would be to add a new property to Static.js "IsSpaceFaring:true/false"

I'd then grab all the spacefaring ones for the top, non spacefaring for the bottom when outputting the ships and ship inputs.

They'd be relatively sorted according to their position in static.js

This would be a very minor change from my end, and would be easy for you to manage

**Comment by ElArGee** [comment]
Technically we can do that now by just adding non space faring vehicles to the end of the ship array in Static.js.

Do we need another property for something that can just be done by hand with the current system? In my opinion we would only really need a space faring property if we are going to add more extensive sorting functionality in the future.

**Comment by Raylehnhoff** [comment]
I think it's worthwhile to just add a flag, personally. It's minor to add
and minor to maintain.

**Comment by ElArGee** [comment]
👍

**Comment by ElArGee** [comment]
Now that the Ursa model is available, should we implement this and add the Ursa and Cyclone?

**Comment by Raylehnhoff** [comment]
Yeah. I'll work something up either tomorrow or next week. I'm in the weeds
on another project that needs to get to beta ASAP.

Can you comment on this chain for which ships would not be spacefaring?
That'll help a lot.

On Aug 27, 2017 12:01 AM, "Loganbacca" <notifications@github.com> wrote:

Now that the Ursa model is available, should we implement this and add the
Ursa and Cyclone?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Raylehnhoff/SCFSD/issues/65#issuecomment-325179040>,
or mute
the thread

**Comment by ElArGee** [comment]
- Ursa
- Cyclone
- Dragonfly
- Nox

**Comment by Raylehnhoff** [comment]
@Loganbacca  -- I added a true/false column for whether a ship is spacefaring or not. This is required, and will put the ship in the right place. Thanks for your help/comments on this.
