### ISSUE TITLE
Dragonfly is a spacefaring spacebike

### ISSUE THREAD

**Issue by t984447** [Raylehnhoff/SCFSD#70]
Hello,
¨
Really small note;
The Dragonfly is categorized under non-space faring vehicle, but that is not correct as it can fly in space. Unlike the NOX or the cars. :)

//Alle090

**Comment by SwiftOmnium** [comment]
Well, the Nox and X1 _can_ fly in space, just like the Dragonfly. They just can't make the transition between planet to space / space to planet (just as the Dragonfly can't). 

Source: https://robertsspaceindustries.com/comm-link/engineering/15991-Q-A-Aopoa-Nox 

But I get your stated problem, as the title of 'Non-Spacefaring Ships' isn't correct. CIG labels these ships nowadays as a 'snub'.

Source: https://robertsspaceindustries.com/ship-matrix

A solution would be to put the non-spacefaring ships in a brand new "Snub Ships" category, and move vehicles like the Rover, Cyclone and Buggy to Non-Spacefaring _Vehicles_, Ground Vehicles or even just Vehicles.

**Comment by ElArGee** [comment]
@Raylehnhoff Can I suggest renaming "Non-Spacefaring Ships" to "Vehicles"?

**Comment by Raylehnhoff** [comment]
Yeah that's probably the best approach.
