### ISSUE TITLE
Missing: Tumbril cyclone

### ISSUE THREAD

**Issue by 0binhex0** [Raylehnhoff/SCFSD#79]

**Comment by SwiftOmnium** [comment]
Hi Loganbacca, is it possible to add all the vehicles instead of just the Cyclone(s)? So this includes the Ursa Rover and the Greycat Buggy. Thanks!

**Comment by ElArGee** [comment]
Cyclone can be done with the current process, but the Ursa and Greycat dont have models in the holoviewer, so haven't been done.

**Comment by SwiftOmnium** [comment]
I don't know if it fits the current process, but they have the Greycat on sketchfab:

https://sketchfab.com/models/1804877e55aa44728074099efc99fc91 

Not the Ursa Rover unfortunately. Thanks for responding and all the hard work though!

**Comment by Raylehnhoff** [comment]
closed by #81

Discussion on the Ursa and Greycat should be confined to #83
