### ISSUE TITLE
WHERE IS MY VULCAN

### ISSUE THREAD

**Issue by DustFingerD3** [Raylehnhoff/SCFSD#89]
Vulcan is missing?

**Comment by SwiftOmnium** [comment]
Jup it is, but there are talks about the 38,5m length being incorrect (more like 45,7). Maybe wait after the Q&A for a correction on this. Just my 2 cents :)

Source: https://www.reddit.com/r/starcitizen/comments/7zqcg7/yts_ship_scale_comparison_tophat_monacle_edition/
